### ISSUE TITLE
How to install it on MacOS?

### ISSUE THREAD

**Issue by PingEnLu** [affenwiesel/matlab-formatter-vscode#1]
How to install it on MacOS?
The path went wrong.

**Comment by affenwiesel** [comment]
Hi, 
what do you mean, when you say 'the path went wrong'?
Did the installing of the extension go wrong or does the formatting not work?

Personally I don't have access to a mac, so I can't check this for myself

**Comment by fasiha** [comment]
On macOS, I see the following: `Could not find path to the mlint executable in the configuration file.` Which is very confusing, I can't see `mlint` mentioned anywhere in the source?

**Comment by fasiha** [comment]
Sorry, I had installed both your module *and* the [Matlab](https://marketplace.visualstudio.com/items?itemName=Gimly81.matlab) module, and it was the latter that was complaining about `mlint`. 🙇‍♂️ sorry!

However, I get `formatting failed` errors, even after setting `matlab-formatter.path` correctly (it seems to default to `  "matlab-formatter.path": "C:\\Users\\Mogli\\.vscode\\extensions\\matlab-formatter\\formatter\\matlab_formatter.py"`?!).

Running `matlab_formatter.py` in the command line on the following Matlab code:
```
x = 1 + 2;y=33;
```
results in a Python error:
```
Traceback (most recent call last):
  File "/Users/ahmed.fasih/Downloads/matlab-formatter-vscode/formatter/matlab_formatter.py", line 188, in <module>
    main(sys.argv[1], indent, start, end)
  File "/Users/ahmed.fasih/Downloads/matlab-formatter-vscode/formatter/matlab_formatter.py", line 135, in main
    m = re.match(p, rlines[0])
IndexError: list index out of range
```

Let me know if I should open a new issue for this.

**Comment by affenwiesel** [comment]
Thanks for finding the bug!

Actually it had nothing to do with the mac! 
I accidently excluded the last line from formatting - which I never realized due to the setting that always adds a newline at the end of a file.

The new version should work as expected
