### ISSUE TITLE
No space insertion when meet the ".^" or "^" operator

### ISSUE THREAD

**Issue by wytWangLei** [affenwiesel/matlab-formatter-vscode#101]
Just as the title says.

**Comment by affenwiesel** [comment]
I have no idea what this is supposed to mean.

**Comment by wytWangLei** [comment]
> I have no idea what this is supposed to mean.

Um, an expression like this 
`f1 = (0.8).^n1;`
The formatter doesn't insert space before and after the operator ".^".
For comparison, 
`f2 = (0.8) .* n2;`
will get the right space insertion.

**Comment by affenwiesel** [comment]
Ah, allright. Yeah that is actually intentional. But I could add an option for that.

**Comment by wytWangLei** [comment]
> Ah, allright. Yeah that is actually intentional. But I could add an option for that.

Thank you for your reply. (By the way, is it because "^" operator has any ambiguous meaning?

**Comment by affenwiesel** [comment]
It's simply personal taste. I initially wrote the formatter just for personal use. And I personally prefer reading e.g. `c * x^3` over `c * x ^ 3`.

**Comment by affenwiesel** [comment]
The corresponding option has been added
