### ISSUE TITLE
Formatting failed

### ISSUE THREAD

**Issue by ChenCuiPlasma** [affenwiesel/matlab-formatter-vscode#104]
Hi, 

I just upgrade to the newest version of the matlab-formatter. However, when I work on my code I just found when I use "ctrl+shift+I", the vs code notifies me that
Formatting failed: File "/home/xxx/.vscode/extensions/affenwiesel.matlab-formatter-2.10.41/formatter/matlab_formatter.py", line 67 pattern = re.compile(fr'(\s*)((\S.*)?)(\{cellOpen}.*$)') ^ SyntaxError: invalid syntax
My system is Ubuntu 16.04 with python 3.5.2 as the default python

**Comment by affenwiesel** [comment]
Hi,

apparently, this is an issue with the python version. The minimum requirement is python 3.6.
I'll update the README.

**Comment by ChenCuiPlasma** [comment]
Thanks a lot
