### ISSUE TITLE
raise : "formatting failed:" and no other tips.

### ISSUE THREAD

**Issue by NGC13009** [affenwiesel/matlab-formatter-vscode#105]
It cannot be used normally. Prompt at the bottom right corner that "formatting failed".
My environment: Windows10, VSC 1.76.0, MATLAB-formatter2.10.41, Python3.9 (based on miniconda, no system Python). MATLAB2019a. 

I think this is a compatibility problem caused by miniconda. My system does not have a direct Python environment. I only installed miniconda and set the base environment of conda to Python 3.9 . Maybe this plug-in doesn't run on conda. i guess. 

plz fix it.

**Comment by affenwiesel** [comment]
My guess is that you didn't specify the correct python path. Have you tried running the script directly from the command line, e.g. `$ python matlab_formatter.py`?

**Comment by jianyshin** [comment]
I encountered the same problem. It looks like remain unworked when i runed the scrpt in the base enviroment in the miniconda. There is a output of "usage: matlab_formatter.py filename [options...]" when i runing the script “matlab_formatter.py”. Can the author provide more suggestions? Thank you !

**Comment by affenwiesel** [comment]
Well, as the output states, the intended usage of the program is to provide at least one command line argument `filename` which should be the path to the file you want to format.

**Comment by affenwiesel** [comment]
By the way, for security reasons, the option to provide a custom python path has been removed in the latest version. Therefore, if you run on windows, you may have to add the path to your python executable to your `PATH`.
