### ISSUE TITLE
switch not indented in the same manner as matlab default

### ISSUE THREAD

**Issue by davidxujiayang** [affenwiesel/matlab-formatter-vscode#11]
Hi, 
This should be a very easy problem. In matlab auto-indenting, the "case" after "switch" will be indented, yet here it is aligned with switch.
Another a bit trick problem is that sequence like && ~ or || ~ that is commonly used in if statements will be collapse into &&~ and ||~, i.e. the space will not be kept. 
Thanks for providing the awesome extension again!

**Comment by affenwiesel** [comment]
Hi,
thanks again for the feedback.
I rewrote the whole python programm to get rid of the swich-case problem.
For the 'not' operator I just removed a special case handling and the spaces are back - however I probably didn't put that special handling in there for nothing (just don't remember ;)). Thus, it might be that there will appear spaces arount a not-operator where you don't want it...

**Comment by davidxujiayang** [comment]
Hi,
Yes I guess I know the reason, now the 'not' operator doesn't work with functions like isfield, isnan, etc. There will be a space between them.

**Comment by davidxujiayang** [comment]
Hi,
I commented on github, but not sure if you will see it since the thread is
closed.  Now the 'not' operator doesn't work with functions like isfield,
isnan, etc. There will be a space between them.

Xu, Jiayang (David)
PhD Candidate
Computational Aerosciences Laboratory
Department of Aerospace Engineering
University of Michigan

**Comment by davidxujiayang** [comment]
Sorry my bad, it works well! Thanks for the update!
Xu, Jiayang (David)
PhD Candidate
Computational Aerosciences Laboratory
Department of Aerospace Engineering
University of Michigan
