### ISSUE TITLE
Wrong operators wrapping with spaces

### ISSUE THREAD

**Issue by vasner** [affenwiesel/matlab-formatter-vscode#111]
With settings:
Matlab-formatter: Add Spaces
Wrapping of operators with spaces.
"all_operations"

Code
```
        double_value = dictionary( ...
            Values.V1S4, 1 / 4, ...
            Values.V1S8, 1 / 8, ...
            Values.V1S16, 1 / 16 ...
        )
```
is changed to 
```
        double_value = dictionary( ...
            Values.V1S4, 1/4, ...
            Values.V1S8, 1/8, ...
            Values.V1S16, 1/16 ...
        )
```

**Comment by affenwiesel** [comment]
I don't see any syntactical errors in the output code. Am I missing something?

**Comment by vasner** [comment]
It for some reasons removes spaces around divide operators when settings are set to add spaces for all operators.

**Comment by affenwiesel** [comment]
Ah, I see. That is actually intentional. Rational numbers are formatted as one single expression, as can be seen in line 9 on the example gif.

**Comment by vasner** [comment]
Understood! Thank you for fast feedback!
