### ISSUE TITLE
formatting failed

### ISSUE THREAD

**Issue by Mar1885** [affenwiesel/matlab-formatter-vscode#113]
formatting failed:
  File "c:\Users\Hongfei Lv\.vscode\extensions\affenwiesel.matlab-formatter-2.11.0/formatter/matlab_formatter.py", line 65
    def cellIndent(self, line, cellOpen:str, cellClose:str, indent):
                                       ^
SyntaxError: invalid syntax

**Comment by affenwiesel** [comment]
I'm assuming that you are running the wrong python version - probably 2.x.
The formatter requires python versison 3.6.
