### ISSUE TITLE
comment will leave a new line between the code

### ISSUE THREAD

**Issue by leewi9** [affenwiesel/matlab-formatter-vscode#12]
before format

![image](https://user-images.githubusercontent.com/10832544/44131375-2e55e20c-a085-11e8-84af-3463dca16c31.png)

after format

![image](https://user-images.githubusercontent.com/10832544/44131380-37e07580-a085-11e8-89af-090fb2881fc0.png)

**Comment by leewi9** [comment]
besides the format for matrix is not perfect, foe example,

```
X = [0 0 1;
0 1 1;
1 0 1;
1 1 1;
];
```

should be formatted to

```
X = [0 0 1;
        0 1 1;
        1 0 1;
        1 1 1;
        ];
```

**Comment by affenwiesel** [comment]
I removed the additional newline after block introducing comments.
The matrix formatting is a little bit trickier, though.
Nevertheless I improved it at least a little bit by indenting the matrix rows after the first one.
If I find the time I will try to improve this further.
