### ISSUE TITLE
Cannot format when parfor exist

### ISSUE THREAD

**Issue by shang-zd** [affenwiesel/matlab-formatter-vscode#13]
The extension will fail to to format when there is a parfor.
A screenshot is enclosed as below.

![failed](https://user-images.githubusercontent.com/14147349/44411874-6af94f80-a55f-11e8-8d21-6cd4feaeb9e0.PNG)

And a demo code for this is below:

`function test = myFun(a, b, c)`
`parfor i = 1:100`
`test = a * i + b * i^2 + c * i^3;`
`end `
`end `

**Comment by affenwiesel** [comment]
Thanks for the feedback.
I added support for the 'parfor' loop in the latest version.
