### ISSUE TITLE
The contents in brackets should not change

### ISSUE THREAD

**Issue by duanguanhua** [affenwiesel/matlab-formatter-vscode#15]
like `fprintf("Working on IRIS data set\n");`
after formatter `fprintf("Working on IRIS data set \ n");`

 "\n" ->"\ n"

**Comment by affenwiesel** [comment]
The reason is that I only implemented the formater to recognize singlequotes as strings e.g. `'string'`.
However, I added support for doublequoted strings in the latest version.
