### ISSUE TITLE
File name cannot contain spaces

### ISSUE THREAD

**Issue by duanguanhua** [affenwiesel/matlab-formatter-vscode#16]
The .m file formatting failed, duo to My username contain spaces. 
extension.js
before
![image](https://user-images.githubusercontent.com/10304151/46473338-64265380-c812-11e8-9b08-783258f527b6.png)
change
![image](https://user-images.githubusercontent.com/10304151/46473117-b61aa980-c811-11e8-8580-5606d672bdab.png)
`let formatter = this.py + "\"" + __dirname + "/formatter/matlab_formatter.py\"";`

**Comment by affenwiesel** [comment]
I added the quotes as per your suggestion
