### ISSUE TITLE
Format multi-line statements with ellipsis correctly

### ISSUE THREAD

**Issue by ajgarn** [affenwiesel/matlab-formatter-vscode#19]
Hi,

A long statement can be broken into multiple lines, and the succeeding lines should then be indented.

Should be:

    s = 1 - 1/2 + 1/3 - 1/4 + 1/5 ...
        - 1/6 + 1/7 - 1/8 + 1/9;

Currently looks like this:

    s = 1 - 1/2 + 1/3 - 1/4 + 1/5 ...
    -1/6 + 1/7 - 1/8 + 1/9;

See [https://se.mathworks.com/help/matlab/matlab_prog/continue-long-statements-on-multiple-lines.html](https://se.mathworks.com/help/matlab/matlab_prog/continue-long-statements-on-multiple-lines.html)

**Comment by affenwiesel** [comment]
Apparently, there is a lot of Matlab functionallity, I don't know ;)
I added the feature in the latest version.

**Comment by ajgarn** [comment]
Awesome! Thanks for the quick response.
