### ISSUE TITLE
Don't use sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='gbk')

### ISSUE THREAD

**Issue by wanzhiyu** [affenwiesel/matlab-formatter-vscode#20]
> sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf8') 
This works really well in Chinese, please don't modify this.
I am not familiar with git and I don't know how to pull request...Sorry.

**Comment by affenwiesel** [comment]
Ok. I just uploaded a new version. Hopefully this deals with the chinese characters issue...
