### ISSUE TITLE
A mistake when writing a matrix including negative numbers

### ISSUE THREAD

**Issue by milkhouse1990** [affenwiesel/matlab-formatter-vscode#21]
When I write a matrix like `[0 -1]`, the formatter will change it to `[0 - 1]`, which means `-1`. Maybe I should add a comma.

**Comment by affenwiesel** [comment]
In the latest version I simply don't format the contents of a vector if the entries are not separated by comma or semicolon. Although this might not be perfect since it results in unformatted code within the square brackets it will at least solve this issue.
