### ISSUE TITLE
How can i format matlab-code in windows 10 ?

### ISSUE THREAD

**Issue by Jia-Calvin** [affenwiesel/matlab-formatter-vscode#23]
![image](https://user-images.githubusercontent.com/18711029/52397312-e6d85b80-2aef-11e9-9400-3b13266a02de.png)

I press the key "shift+alt+F", the formatter gets the issue, "formatting failed". There are not python3 in my system. Is this the reason?

**Comment by affenwiesel** [comment]
Since the only Requirement which is listed for this plugin is Python3, this is obviously a requirement ...

**Comment by Jia-Calvin** [comment]
Thanks.
