### ISSUE TITLE
Too much indentation with line continuation in nested functions

### ISSUE THREAD

**Issue by noirchen** [affenwiesel/matlab-formatter-vscode#24]
When line continuation (...) is used in a nested function, the `indent` function will cause too much indentation. For example,

    function fun

    s = [1,2,3;
    4,5, 6];

    end
is formatted to

    function fun
    
        s = [1, 2, 3;
            4, 5, 6];
    
    end
which is fine, but

    function fun_a

        function fun_b

            s = [1, 2, 3;
            4, 5, 6];

        end

    end
is formatted to

    function fun_a

        function fun_b

            s = [1, 2, 3;
                    4, 5, 6];

        end

    end

which is too much. And with line continuation, the indentation can become even larger

    function fun_a

        function fun_b

            s = [1, 2, 3; 4, ...
            5, 6];

        end

    end
is formatted to

    function fun_a

        function fun_b

            s = [1, 2, 3; 4, ...
                        5, 6];

        end

    end

**Comment by noirchen** [comment]
It seems that this is because the script does not remove the original indentation, and simply adds new indentation. Should be easy to fix by first unindenting all lines.

**Comment by affenwiesel** [comment]
Thanks for the remark.
I changed the behaviour such that multiline matrices will be intended correctly now. If you combine them with an elliplis however, an aditional indentation will be added. e.g.
```
M = [1,2,3;...
4,5,6;
7,8,9]
```
will become
```
M = [1,2,3;...
        4,5,6;
    7,8,9]
```
