### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by hexiaoqiu** [affenwiesel/matlab-formatter-vscode#31]
I didn't see any method to use thismatlab-formatter-vscode!
Shall I press which combination of keys to format my code?
It seems that all users are genius which know anything before they are born....

**Comment by affenwiesel** [comment]
Right click -> format document ....

**Comment by hexiaoqiu** [comment]
Thank you very much~! @AlexanderLieret 
Please forgive me the emotional language I used!
I really appreciate your work, thank you again!
