### ISSUE TITLE
Code with line continuation got formatted incorrectly in the latest version 

### ISSUE THREAD

**Issue by soraros** [affenwiesel/matlab-formatter-vscode#33]
```Matlab
h = @(x0, c) ...
    (abs(xx - x0) <= re / 2) .* (re - sqrt(re.^2 - (xx - x0).^2) + c) ...
+(abs(xx - x0) > re / 2);

h = @(x0, c) ...
    (abs(xx - x0) > re / 2) ...
    +(abs(xx - x0) <= re / 2) .* (re - sqrt(re.^2 - (xx - x0).^2) + c);
```
Please note that only the first one fails.

**Comment by soraros** [comment]
Things stops working after [this commit](https://github.com/affenwiesel/matlab-formatter-vscode/commit/9f884e2e502feb97345be564636af23844a1230e).

**Comment by soraros** [comment]
Here is a minimised example
```matlab
a ...
    +b .+ c ...
+d;
```

**Comment by affenwiesel** [comment]
Fixed

**Comment by soraros** [comment]
This code still doesn't seem to work

```coq
error('%', ...
a)
```

**Comment by affenwiesel** [comment]
Another corner case I didn't consider.

**Comment by soraros** [comment]
Thanks again!

**Comment by soraros** [comment]
@affenwiesel and bad news again
```matlab
error('''%f', ...
a)
```

**Comment by soraros** [comment]
and this also
```matlab
'+'''
```
it got formatted into
```matlab
' + '''
```

**Comment by affenwiesel** [comment]
That's actually a different problem caused by the quotes inside the string. I uploaded a fix for this, however this might lead to bad formatting of actual empty strings. Since I don't see a reason why anyone should need those in their code I think most of you should be happy with this fix ;)

**Comment by soraros** [comment]
> That's actually a different problem caused by the quotes inside the string.

Yes, I'm aware of that. I'm just not sure whether it's worth an independent issue due to the lack of usefulness. But I think those things may occur in need of more user-friendly error message.

Anyway, thanks a lot!
