### ISSUE TITLE
formatter removes space that shouldn't be removed

### ISSUE THREAD

**Issue by rick3rt** [affenwiesel/matlab-formatter-vscode#36]
I have another (perhaps kinda weird) formatting issue. In the following example:
```
tv = (0:0.1:10).';
f = @(t, a) a .* t;
a = [tv*1e3 f(tv, 1)];
```
the last line is formatted to:
```
a = [tv * 1e3f(tv, 1)];
```

This only occurs if `f` has more than one input argument, i.e. 
```
f = @(t) 5 .* t;
a = [tv*1e3 f(tv)];
```
works fine.

**Comment by ocehugo** [comment]
Yes, I can confirm this:

```matlab
abc = ['a' 'b' 'c'] ; % abc='abc'
```

if applying the formatter we got:
```matlab
abc = ['a''b''c']; % abc='a'b'c'
```


Another case of wrong removal of whitespace:
```matlab
switch 'abc'
   case 'abc' %abc
end
```

This turns into:
```matlab
switch 'abc'
    case 'abc'%abc 
end
```

**Comment by affenwiesel** [comment]
Fixed in latest update
