### ISSUE TITLE
Variable end with 'end' will be formatted uncorrectly

### ISSUE THREAD

**Issue by Chivier** [affenwiesel/matlab-formatter-vscode#38]
Using a variable end with 'end', such as 'i_end', will lead to uncorrect formmat code.

example:
test.m
```matlab
for k = d_st:d_end
    t = a * k ...
        +b .* k^2 ...
        +c * k^3

    if norm(t)% ADD NEWLINE BEFORE AND AFTER BLOCK
        fprintf('t>0')
    end
end
```

This code cannot be formatted.

Error information like this:
```
Traceback (most recent call last):
  File "./matlab_formatter.py", line 309, in <module>
    main()
  File "./matlab_formatter.py", line 305, in main
    formatter.formatFile(sys.argv[1], start, end)
  File "./matlab_formatter.py", line 258, in formatFile
    (offset, line) = self.formatLine(line)
  File "./matlab_formatter.py", line 217, in formatLine
    step = self.istep.pop()
IndexError: pop from empty list
```

**Comment by Chivier** [comment]
I guess we need to modify the pattern. More exactly, 15th line in the code.

```python
ctrlend = r'(^|\s*)(end|endfunction|endif|endwhile|endfor|endswitch)(\s+\S.*|$)'
```

**Comment by Chivier** [comment]
I pulled a request trying to fix this.

**Comment by Chivier** [comment]
Also I think there is another problem:

This pattern, `(^|\s*)`, is a little strange. And I think `(^|\s+)` is correct.

**Comment by affenwiesel** [comment]
Hi, I'll try to revise the open pull requests over christmas.
Thanks for contributing!

**Comment by affenwiesel** [comment]
Took a while longer than expected ;)
Since I'm a dad I don't have too much time left for stuff like this. I hope you guys understand.
However I just released a new version, where this bug is fixed.
Again, thanks for the contribution!
