### ISSUE TITLE
Chinese comments gibberish

### ISSUE THREAD

**Issue by mousefire1** [affenwiesel/matlab-formatter-vscode#4]
With a file including Chinese comment, the formatter changed the comments to gibberish...

**Comment by affenwiesel** [comment]
I suppose that this might be an issue with the encoding module of the python library.
I just ran the formatter on some random chinese letters (排要美布不機家):
On anaconda - pyhon 3.6.3 under windows it crashed with the following error: 
```
File "C:\Users\Mogli\Programme\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 39: character maps to <undefined>
```
On python 3.5.2 on linux it just did the formatting without any errors.

So I assume that your error might also be related to this problem. Therefore I probably won't be able to fix this. 
Maybe you should try using a different python version and see what happends...
Or maybe someone else has any idea?

**Comment by mousefire1** [comment]
Yes, I ran it on windows...

**Comment by mousefire1** [comment]
I think maybe I found the problem. Matlab on windows encode with "gbk" by default. But I can't solve the problem as not familiar with python..

**Comment by duanguanhua** [comment]
`import io
import sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf8')`
You can add this code into **matlab_formatter.py** in **C:\Users\<Your username>\.vscode\extensions\affenwiesel.matlab-formatter-2.2.3\formatter\matlab_formatter.py**

**Comment by affenwiesel** [comment]
Still running into the same error.

**Comment by duanguanhua** [comment]
**import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='gbk')**
This will work. I hava test it.

**Comment by affenwiesel** [comment]
Nope.
Still the same error as before.
However, it might solve the problem mousefire1 originally described.
But since I wasn't able to reproduce this one in the first place I can't tell.

**Comment by milkhouse1990** [comment]
On Windows, the default encoding depends on the system locale, which can be accessed via the Control Panel. I think that if I can get the encoding of the `.m` file, the problem will be solved, but I don't know how.

**Comment by CSGlobalOffensive** [comment]
Thanks very much!
```python
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf8')
```
Just cancel these comments and it will work.

**Comment by wanheyang2017** [comment]
guys, I have the same problems as yours. But I finally find the solution after I read your response.Firstly add the code `sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf8')`, and then modify the code  `with open(filename, 'r') as f:` in line 231,change it to the new code `with open(filename, 'r', encoding='utf8') as f:` , and it succeed, there you go,guys.
