### ISSUE TITLE
Using spaces to separate numbers in matrix leads to format error.

### ISSUE THREAD

**Issue by Chivier** [affenwiesel/matlab-formatter-vscode#40]
There is still another a problem.
As we all know that we have two method to separate numbers in a matrix. The first method is using ',', such as [3, 4, 5]. The other is separating numbers with a space, and this will lead to incorrect formatted code.

For example, `[1 -i]` will be formatted as `[1 - i]`.

I have 2 suggestions. The first is we need to create a new pattern to recognize complex number. The other is when we recognize a assignment to a matrix, we need to find whether there is ',' in the rvalue.

**Comment by Chivier** [comment]
I have pulled a request to solve this (^_^).

**Comment by affenwiesel** [comment]
Fixed in latest update.
@Chivier Thanks for the contribution. I found a better way to deal with the issue, though. Now it also works for non-comma-separated multiline matrices!
