### ISSUE TITLE
Running Save Participants for '*.m': Formatting

### ISSUE THREAD

**Issue by happyTonakai** [affenwiesel/matlab-formatter-vscode#42]
Today vscode is updated to 1.42.0 and matlab-formatter fails in this version. It worked well yesterday.

Whenever I save my m-file, there is a notification saying `Running Save Participants for '*.m': Formatting` and I couldn't even save my file. The only thing I can do to save the file is clicking Cancel.
<img width="409" alt="批注 2020-02-07 164604" src="https://user-images.githubusercontent.com/21305646/74015072-e4dafe00-49ca-11ea-9f99-5407ad842791.png">

Here is the official description from vscode team:
<img width="715" alt="批注 2020-02-07 170010" src="https://user-images.githubusercontent.com/21305646/74015318-574bde00-49cb-11ea-8f6f-b8c4730ef019.png">

**Comment by TheLaas** [comment]
I also started having this issue today.

**Comment by RobinTournemenne** [comment]
Same here. I tried to debug your extension but was unable to understand what happened. I think they changed some things regarding the document.save() method.

**Comment by RobinTournemenne** [comment]
I think I solved the problem, copying the microsoft python extension code for formatter. There was an issue with asynchrone code I think. I am doing a pull request, here is the link if you want to change the code in the folder ~/.vscode/extensions/affenwiesel.matlab-formatter-2.4.12/extension.js

https://github.com/affenwiesel/matlab-formatter-vscode/pull/43

**Comment by happyTonakai** [comment]
Great! It works for me as well. Thanks @RobinTournemenne

**Comment by RobinTournemenne** [comment]
Nope it does not... I did not correct the bug... I add to remove format on save, format on type and format on paste in the vscode settings. Somehow the extension wants to format before changes has been made to the buffer or the saving process!
