### ISSUE TITLE
some suggestion about multi-language (Chinese)

### ISSUE THREAD

**Issue by ilcpm** [affenwiesel/matlab-formatter-vscode#44]
I don't know how the problems happen, and I have read the two issue about Chinese.
I see someone have contributed some code for the project, but actually it doesn't work for Chinese no matter what kind of code the file use, at present.

My suggestion is to provide a setting so users can choose which code they use. Then treat the file in that code and return the formatted text in that code.
For Chinese, Matlab use GBK code, maybe change it into UTF-8 for python to use and then change the result from UTF-8 into GBK can be a solution.

(sorry for my poor English)

**Comment by affenwiesel** [comment]
Hopefully with Matlab supporting utf-8 now, the latest update works for you guys.
If so it would be nice to hear from you.

**Comment by ilcpm** [comment]
I'm glad to receive your reply. But when I try to format a file named `test.m`
```matlab
fprintf('123中文测试abc\n')
```
encode in utf-8 without Bom

An error happend
```
formatting failed
Traceback (most recent call last):
  File "c:\Users\Ruossipha\.vscode\extensions\affenwiesel.matlab-formatter-2.5.0/formatter/matlab_formatter.py", line 301, in <module>
    main()
  File "c:\Users\Ruossipha\.vscode\extensions\affenwiesel.matlab-formatter-2.5.0/formatter/matlab_formatter.py", line 298, in main
    formatter.formatFile(sys.argv[1], start, end)
  File "c:\Users\Ruossipha\.vscode\extensions\affenwiesel.matlab-formatter-2.5.0/formatter/matlab_formatter.py", line 277, in formatFile
    print(line)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcad' in position 13: surrogates not allowed
```
there is no non-ASCII character in the file path

**Comment by ilcpm** [comment]
System Info:
Windows 10 1909 x64
Matlab: 2019b
Python: 3.7 x64

**Comment by ilcpm** [comment]
in version 2.5.2, now I can successfully format codes with Chinese encode with `GBK`.
Thanks for your work😀
