### ISSUE TITLE
Formatting matrix bug

### ISSUE THREAD

**Issue by chaoxL** [affenwiesel/matlab-formatter-vscode#47]
For example:
Before:
`    qConj = [q(:, 1) -q(:, 2) -q(:, 3) -q(:, 4)];`

After:
`    qConj = [q(:, 1) - q(:, 2) - q(:, 3) - q(:, 4)];`

There is an extra space between "-" and "q(:, 2)" which makes some error when debugging

**Comment by affenwiesel** [comment]
Fixed in the latest update
