### ISSUE TITLE
Fix Support for UTF-8

### ISSUE THREAD

**Issue by b4imetu** [affenwiesel/matlab-formatter-vscode#49]
MATLAB R2020a now support UTF-8 by default, please fix the support for UTF-8
Issues unsettled for now
- Unable to format UTF-8 file
- When formating GBK, Chinese characters go like �������

**Comment by diverger** [comment]
Yes. It seems it will force the encoding to UTF-8 when formatting (?). So if your encoding is not UTF-8, the text will be unreadable after formatting.

**Comment by affenwiesel** [comment]
Fixed in the lates update.
