### ISSUE TITLE
matlab-formatter gets stuck when format on save enabled

### ISSUE THREAD

**Issue by nash169** [affenwiesel/matlab-formatter-vscode#50]
Hi,
I'm testing the package that seems to work fine when I format the doc manually. I would like to format the doc automatically on save. I activated editor.formatOnSave but whenever I save the file the notification window with "Running matlab-formatter" appears and it stays there neither formatting nor saving the file. I'm working on Ubuntu 18 machine. Is there a solution for this?

Thanks

**Comment by affenwiesel** [comment]
Duplicate of #42
