### ISSUE TITLE
Setup python path

### ISSUE THREAD

**Issue by BirukTes** [affenwiesel/matlab-formatter-vscode#52]
Hi,
 
It is possible to indicate where python is saved/path? For example, here is from Python MS ext:
`python.pythonPath`

Many thanks.

**Comment by affenwiesel** [comment]
I don't think I get the question. Do you want to know where your python executable is located? And if so, what does this have to do with my extension?

**Comment by BirukTes** [comment]
@affenwiesel I mean that I have portable python source code/exe, and I would like to set the path/location which your extension uses instead of the environment variable.

**Comment by affenwiesel** [comment]
Ah, thanks for clarifying.
That might indeed be a usefull option for some users.
So I just added it for the latest update.
Thanks for the feedback!
