### ISSUE TITLE
New line before and after loops undesired

### ISSUE THREAD

**Issue by Galileji** [affenwiesel/matlab-formatter-vscode#54]
I noticed that the formatter inserts new lines before and after for loops, if/else statements and so on. Are you sure this is the intended behaviour for most users?
In my case I would be able to decide not to do that, because when you have plenty of such conditions the formatted code will become much much lenghtier.

**Comment by affenwiesel** [comment]
Hi, thanks for the feedback!
I just added an option for the user to choose if additional newlines shall be added.

**Comment by Galileji** [comment]
Thank you so much for your beautiful work and quick response :)
