### ISSUE TITLE
Incorrectly formats imports

### ISSUE THREAD

**Issue by NoahBres** [affenwiesel/matlab-formatter-vscode#57]
The formatter incorrectly inserts spaces into import statements.

Correct syntax:
`import util.*`

Formatted syntax:
`import util .*`
The formatter will add a space after the package name which makes the import invalid.

Thank you! The formatter is great!

**Comment by affenwiesel** [comment]
Hi, I just released a fix.
If you like the formatter, I'd appreciate feedback at https://marketplace.visualstudio.com/items?itemName=AffenWiesel.matlab-formatter&ssr=false#review-details

**Comment by NoahBres** [comment]
Left a review! Thank you!
