### ISSUE TITLE
Suggestion: Ignore line(s)

### ISSUE THREAD

**Issue by NoahBres** [affenwiesel/matlab-formatter-vscode#58]
Suggestion to add an ignore option on specific lines using comments to skip over formatting.
Something like the following:

```
foo = bar; % This line should be formatted

% ignore-start
a = [ 1, 2, 3 ];     % This line should not be formatted
% ignore-end
```

Or possibly something like this:
```
% ignore-next
a = [ 1, 2, 3 ];    % This line should not be formatted

b = 5 + 3;         % This line should be formatted
```

This would alleviate issue #57

**Comment by affenwiesel** [comment]
I'll think about including this

**Comment by affenwiesel** [comment]
Feature has been added in the latest release.
