### ISSUE TITLE
format issue

### ISSUE THREAD

**Issue by ycliu2020** [affenwiesel/matlab-formatter-vscode#63]
My code below here:
`title({[mlabels.component{varNum}, mlabels.unite{varNum}]; ['spatial cc = ', num2str(yr_cc{varNum})]}, 'Interpreter', 'latex', 'fontsize', 10); % cc=',num2str(corr))
hold on
c = colorbar;
% c.TickLength = 0.0245;
c.Ticks = colorbar_Series(2:end - 1);
c.Limits = [min(colorbar_Series) max(colorbar_Series)];`
when shift+alt+F, it become:
title({[mlabels.component{varNum}, mlabels.unite{varNum}]; ['spatial cc = ', num2str(yr_cc{varNum})]}, 'Interpreter', 'latex', 'fontsize', 10); % cc=',num2str(corr))
[space] [space] [space] [space] [space] hold on
[space] [space] [space] [space] [space] c = colorbar;
% c.TickLength = 0.0245;
[space] [space] [space] [space] [space] c.Ticks = colorbar_Series(2:end - 1);
[space] [space] [space] [space] [space] c.Limits = [min(colorbar_Series) max(colorbar_Series)];
i.e. the beginning of line after 'title(..)' have too many spacings, it will be bad in the loop/if case, because the code 'end' after this line will not align at 'for' in the beginning;
even so, Thanks to the author for the convenience. why gitHub didint display spacing :(

**Comment by affenwiesel** [comment]
So if I understand you correctly: 
This is the code before formatting:
```
title({[mlabels.component{varNum}, mlabels.unite{varNum}]; ['spatial cc = ', num2str(yr_cc{varNum})]}, 'Interpreter', 'latex', 'fontsize', 10);
% cc=',num2str(corr))
hold on
c = colorbar;
% c.TickLength = 0.0245;
c.Ticks = colorbar_Series(2:end - 1);
c.Limits = [min(colorbar_Series) max(colorbar_Series)];
```
And this is how it is formatted:
```
title({[mlabels.component{varNum}, mlabels.unite{varNum}]; ['spatial cc = ', num2str(yr_cc{varNum})]}, 'Interpreter', 'latex', 'fontsize', 10);
% cc=',num2str(corr))
     hold on
     c = colorbar;
% c.TickLength = 0.0245;
     c.Ticks = colorbar_Series(2:end - 1);
     c.Limits = [min(colorbar_Series) max(colorbar_Series)];
```
Is that correct?
Which version of python are you using?

**Comment by ycliu2020** [comment]
actually, the source code is: 
```title({[mlabels.component{varNum}, mlabels.unite{varNum}]; ['spatial cc = ', num2str(yr_cc{varNum})]}, 'Interpreter', 'latex', 'fontsize', 10);% cc=',num2str(corr))```
```hold on```
```c = colorbar;```
```% c.TickLength = 0.0245;```
`c.Ticks = colorbar_Series(2:end - 1);`
`c.Limits = [min(colorbar_Series) max(colorbar_Series)];`
when formatted, it will become:
```title({[mlabels.component{varNum}, mlabels.unite{varNum}]; ['spatial cc = ', num2str(yr_cc{varNum})]}, 'Interpreter', 'latex', 'fontsize', 10);% cc=',num2str(corr))```
```                                                                                     hold on```
```                                                                                     c = colorbar;```
```% c.TickLength = 0.0245;```
`                                                                                       c.Ticks = colorbar_Series(2:end - 1);`
`                                                                                       c.Limits = [min(colorbar_Series) max(colorbar_Series)];`
but when the comment is written to the next line, the format is right. i.e:
```title({[mlabels.component{varNum}, mlabels.unite{varNum}]; ['spatial cc = ', num2str(yr_cc{varNum})]}, 'Interpreter', 'latex', 'fontsize', 10);% cc=',num2str(corr))```
```% cc=',num2str(corr))```
```hold on```
```c = colorbar;```
```% c.TickLength = 0.0245;```
`c.Ticks = colorbar_Series(2:end - 1);`
`c.Limits = [min(colorbar_Series) max(colorbar_Series)];`
My python version is 3.7.6. Thx for reminding

**Comment by affenwiesel** [comment]
Thanks for reporting back.
The issue was the quote in the comment. This completely confused the interpretation of the entire line.
Fixed in the latest update (hopefully without sideeffects ;))
