### ISSUE TITLE
Error when formatting

### ISSUE THREAD

**Issue by erhmeh** [affenwiesel/matlab-formatter-vscode#65]
\affenwiesel.matlab-formatter-2.8.3/formatter/matlab_formatter.py", line 344 print('%s%s' %(usage,opt), file=sys.stderr) ^ SyntaxError: invalid syntax

**Comment by affenwiesel** [comment]
I think I need a little bit more information...
Which version of python are you using?

**Comment by yi-Xu-0100** [comment]
@affenwiesel I have got the same error. The follow is my environment.

Python 2.7.15
win10 professional edition 19041.630

Do I need to install a higher version of python and indicate the location in the configuration?

**Comment by yi-Xu-0100** [comment]
I solve it by using the python3.7(I installed before) and set the `Python path`.

Then I got the same error of #55. With the help of WhiskyChoy(#67). I added space after the customized python path.

Finally, it gets worked.

**Comment by affenwiesel** [comment]
Fix included in latest version.
