### ISSUE TITLE
Unknown character inserted at beginning of file after formatting

### ISSUE THREAD

**Issue by FYPetro** [affenwiesel/matlab-formatter-vscode#7]
Before formatting: ![image](https://user-images.githubusercontent.com/5100887/40756657-452c2bc6-64b7-11e8-95c0-a321047c3c15.png)

After formatting: ![image](https://user-images.githubusercontent.com/5100887/40756680-60c426f4-64b7-11e8-83bd-9657f40cc5da.png)

Encoding: UTF-8

**Comment by affenwiesel** [comment]
Maybe there was some strange invisible character at the beginning of the file before formatting?
From just copy-pasting your snipped I can not reproduce this error.

**Comment by FYPetro** [comment]
I think it's because MATLAB supports UTF-8 (without BOM) but the encoding I had been using was UTF-8. I've converted all my code files to UTF-8 (without BOM).
