### ISSUE TITLE
[Suggestion] Publish to PYPI

### ISSUE THREAD

**Issue by tiagovla** [affenwiesel/matlab-formatter-vscode#72]
Could you put it on PYPI? It would be nice to use it with vim.

**Comment by affenwiesel** [comment]
I'm not familiar with PYPI and ever since I got a baby daughter I hardly have time for this project anyway.
Therefore, I'd rather not put any additonal effort into this unless it's about fixing bugs.
However, it's free software, so feel free to publish it on PYPI yourself.
