### ISSUE TITLE
#request There is no formatter for 'objective-c' files installed.

### ISSUE THREAD

**Issue by b4imetu** [affenwiesel/matlab-formatter-vscode#73]
After installation, I don't know how to format my `.m` code.
When using `Shift+Alt+F` :
`There is no formatter for 'objective-c' files installed.`
![Snipaste_2020-12-18_00-28-14](https://user-images.githubusercontent.com/41535001/102515327-86b88600-4085-11eb-8a79-780e46f2a564.jpg)
Time to Update README.md to give a "the babysitter" how-to-use tutorial.
Thx a lot

python --version
Python 3.9.0

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by b4imetu** [comment]
Solved.
Change your `.m` files' language to MATLAB
![image](https://user-images.githubusercontent.com/41535001/102516893-4954f800-4087-11eb-9cda-52a6f003c8bd.png)
I didn't know I need to do that.
Please update `README` to let this stupid question confuse more people <3

**Comment by affenwiesel** [comment]
If you have the VSCode MATLAB extension installed, .m files should be identified as MATLAB files automatically.
