### ISSUE TITLE
formatting failed the filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by brnold** [affenwiesel/matlab-formatter-vscode#74]
Hi, 

I'm on windows 10. I set the python path to "C:\Users\MYUSERNAME\Anaconda3\python.exe"

and I get the message "formatting failed the filename, directory name, or volume label syntax is incorrect"

What am I doing wrong?

Thanks,

**Comment by affenwiesel** [comment]
This should be fixed in the latest version.
Please let me know whether this is the case.
