### ISSUE TITLE
bug solution or docs suggestion for formatting failed

### ISSUE THREAD

**Issue by Jebearssica** [affenwiesel/matlab-formatter-vscode#75]
vscode information is as below, and use the latest version of matlab-formatter-vscode

```shell
version: 1.52.1 (system setup)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

It did not work on whether UTF-8 or GB2312 or Windows 1256, whether contains Chinese character or not, so it may have nothing to do with the encoding.

I did not change the setting, which means Formatter path and Python path are all empty. Although the introduction shows they are both optional, the users should expected to set the correct **python.exe** path in Python path settings. And it works for me. So it may be better to change the setting introductions :)

**Comment by Jebearssica** [comment]
https://github.com/affenwiesel/matlab-formatter-vscode/blob/d46e12431a3ffdc2ab065446b7430f818cd35026/package.json#L43

**Comment by affenwiesel** [comment]
Bug fixed!
