### ISSUE TITLE
try; catch; end one liner support missing

### ISSUE THREAD

**Issue by SiFreZi** [affenwiesel/matlab-formatter-vscode#78]
Hi,
I like this extenstion very much. Regrettably the extension does not support try; catch; end one liner statements.
The 'end' is not recognized and the indentation is buggy.
`try something; catch e; end`
I'd love to see an update here.
Best regards,
Simon

**Comment by affenwiesel** [comment]
Hi,
thanks for the feedback. I added the requested feature and it should be available in the latest version.
