### ISSUE TITLE
Formatting classdef does not work

### ISSUE THREAD

**Issue by provinzio** [affenwiesel/matlab-formatter-vscode#89]
I am using `matlab-formatter` v2.9.0 and get the following result, when formatting a classdef.
The method functions aren't indented correctly.

```
classdef Test

    properties
        A
    end

    methods
        function obj = Test(a)
        obj.A = a;
    end

end

end
```

I would expect something like this

```
classdef Test

    properties
        A
    end

    methods
        function obj = Test(a)
            obj.A = a;
        end
    end

end
```

EDIT:
or actually expect this, because I want my functions content not indented. Therefore, classdef should'nt be indented either.

```
classdef Test

properties
    A
end

methods
    function obj = Test(a)
        obj.A = a;
    end

end

end
```

**Comment by affenwiesel** [comment]
To get the version with everything indented, simply set `indent mode` to `all_functions`.
Otherwise functions will not be indented. 
Getting the version with classdef not indeted, would require extending the `indent mode` feature.

**Comment by affenwiesel** [comment]
Allright -- turned out to require only a minor adjustment.
In the latest version, your desired formatting behavior can be achieved by setting `indent mode` to `only_nested_functions`.
