### ISSUE TITLE
`formatting warning: There are more end-statements than blocks!` `if` statement, maybe because paired with `all`

### ISSUE THREAD

**Issue by sgbaird** [affenwiesel/matlab-formatter-vscode#92]
`formatting warning: There are more end-statements than blocks!`

Following line was giving me grief:
```matlab
if all(abs(projpts(:, end - ndegdim + 1:ndim)) < tol, 'all')
    projpts = projpts(:, 1:ndim - ndegdim);
end
```
Swapped to:
```matlab
check_tol = all(abs(projpts(:, end - ndegdim + 1:ndim)) < tol, 'all');

if check_tol
    projpts = projpts(:, 1:ndim - ndegdim);
end
```
Seems to work OK now.

It was recognizing the use of `end` after the `if` as the kind of `end` that goes after an `if` statement/function/etc.

**Comment by affenwiesel** [comment]
Yeah, the problem is, that each occurence of the keyword `end` is treated as an `end of block`. I also don't have an idea how to fix this without changing the entire logic of the formatter to something more involved.
