### ISSUE TITLE
Spaced added inside string

### ISSUE THREAD

**Issue by SiFreZi** [affenwiesel/matlab-formatter-vscode#93]
Hello,

regrettably the formatter adds spaces inside of strings:

`cmd = ['im createissue --type="Test Session" ' obj.baseParams ' ' fieldsAndValues];`

becomes

`cmd = ['im createissue -- type = "Test Session"' obj.baseParams ' ' fieldsAndValues];`

which breaks the commandline in this case.
Is it possible to change that behaviour?

Regards,
Simon

**Comment by affenwiesel** [comment]
Fixed
