### ISSUE TITLE
Enhancement request: User preference on how to indent line continuations for multi-row objects with { or [

### ISSUE THREAD

**Issue by MSLeiter** [affenwiesel/matlab-formatter-vscode#98]
Right now, the formatter forces multi-row items within curly {} or square brackets [] to align with the item above it, for example:

![image](https://user-images.githubusercontent.com/101780176/190226967-e5735e97-8320-45ca-abf8-c99288c24e7e.png)

However, as can be seen, when it is function arguments, it aligns with a single indent.

The "aligned indent" for { and [ objects can push everything out a long way if there are a lot of lead in characters. If the lines themselves are long, or your available space in editors is small, this causes things to shift off the screen, or worse yet, starts word-wrapping everything. For example, the following is not too bad, but you get the idea:

![image](https://user-images.githubusercontent.com/101780176/190227445-15a74dce-c8ad-4666-ba3b-332db80adf16.png)

I would much prefer normal indentation on everything - just indent one additional indent from whatever the current indent count is. This is how I format all my non-matlab code and it works great.

Please add an option on how to indent these use cases, if not just changing the default to match how function arguments work. Since that would cause reformatting for existing users, probably the option is better.

Note that the normal VS Code editor provides multiple options for some use cases similar to this. For example, with word wrap, you can decide to not indent, indent one extra time, or double-indent (which makes the word wraps stand out more). May want to consider multiple options like that for this case.

Thanks!!

**Comment by affenwiesel** [comment]
Option has been added in 2.10.41
